services:
  admin:
    image: jeevanugale/admin_service:bugfix-01-09611be471534f55b7fcfc7c35cc2246c398c8da
    container_name: admin
    ports:
      - "5003:5003"
    env_file:
      - .env

  user:
    image: jeevanugale/user_service:bugfix-01-09611be471534f55b7fcfc7c35cc2246c398c8da
    container_name: user
    ports:
      - "5002:5002"
    env_file:
      - .env

  auth:
    image: jeevanugale/auth_service:bugfix-01-09611be471534f55b7fcfc7c35cc2246c398c8da
    container_name: auth
    ports:
      - "5001:5001"
    env_file:
      - .env

  web:
    image: jeevanugale/web_frontend:bugfix-01-09611be471534f55b7fcfc7c35cc2246c398c8da
    container_name: web
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - admin
      - user
      - auth